# SF_Routing File
# Global routing definitions

index:
  url: /
  param: { module: index, action: index }

cms:
  url: /cms
  param: { module: cms, action: index }

#blog_roll:
#  url: /blogs
#  param: { module: blog, action: blogRoll }

blog_listing:
  url: /blog/:blogName
  param: { module: blog, action: index }
  requirements: { blogName: '[A-Za-z0-9-+]+' }

blog_single:
  url: /blog/:blogName/:title/:postId
  param: { module: blog, action: single }
  requirements: { blogName: '[A-Za-z0-9-+]+', title: '[A-Za-z0-9-+]+', postId: '[0-9]+' }